import Foundation

// Compile this file as main.swift alongside SignedFirmware.swift.
// Supply a signed envelope generated by the publisher's trusted key.
let fixture = CommandLine.arguments.dropFirst().first ?? ""
guard !fixture.isEmpty else {
    fatalError("Usage: signature-smoke-test /path/to/signed-envelope.json")
}
let data = try Data(contentsOf: URL(fileURLWithPath: fixture))
let envelope = try JSONDecoder().decode(SignedFirmwareEnvelope.self, from: data)
guard SignedFirmwareVerifier.verify(envelope) else {
    fatalError("Valid signed fixture rejected")
}
let payload = envelope.payload
let altered = SignedFirmwarePayload(
    product: payload.product, version: payload.version + "-tampered",
    build: payload.build, hardware_profile: payload.hardware_profile,
    idf: payload.idf, image_url: payload.image_url,
    sha256: payload.sha256, minimum_allowed_version: payload.minimum_allowed_version,
    release_notes: payload.release_notes
)
let invalid = SignedFirmwareEnvelope(
    signature_format: envelope.signature_format, key_id: envelope.key_id,
    payload: altered, signature: envelope.signature
)
guard !SignedFirmwareVerifier.verify(invalid) else {
    fatalError("Tampered fixture accepted")
}
print("PASS: authentic release accepted; tampered release rejected")
